/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "Scaffolding"
include(":scaffolding-core")
include(":scaffolding-editor")